# Training configuration for Pattern Shape prediction model - LOCAL VERSION
# (part I of NeuralTailor)
# Optimized for local training on Mac or single GPU systems

experiment:
  project_name: FashableTechpack
  run_name: LocalTraining
  run_id: 
  local_dir: outputs/checkpoints
  is_training: True
  save_checkpoint_steps: 10  # Save checkpoints more frequently for local testing
  save_checkpoint_epochs: 1  # Save a checkpoint every epoch

# ----- Dataset-related properties -----
dataset: 
  class: GarmentDetrDataset
  wrapper: RealisticDatasetDetrWrapper

  max_pattern_len: 23   # Overridden if panel_classification is specified
  max_panel_len: 14
  max_num_stitches: 28   # when training with stitches
  max_stitch_edges: 56

  element_size: 4
  rotation_size: 4
  translation_size: 3
  use_sim: true
  use_smpl_loss: true
  img_size: 512  # Reduced image size for local training
  augment: true

  panel_classification: ./data_configs/panel_classes_condenced.json 
  filter_by_params: ./data_configs/param_filter.json
    
  standardize:
    gt_scale:
      outlines: [26.674109  , 29.560705,  1,  1]
      rotations: [1.3826834, 1.9238795, 1.2877939, 1.       ]
      stitch_tags: [119.964195, 109.62911, 105.657364]
      translations: [109.58753, 51.449017, 37.846794]
    gt_shift:
      outlines: [0., 0., 0, 0]
      rotations: [-0.38268343, -0.9238795, -1.,  0.]
      stitch_tags: [-59.99474 , -78.23346 , -52.926674]   
      translations: [-55.25636 , -20.001333, -17.086796]

data_split:
  type: percent
  split_on: folder
  valid_per_type: 10
  test_per_type: 80  # Use more data for training in local mode

# ----- Network Architecture --------
NN:
  pre-trained:  
  step-trained: 
  model: GarmentDETRv6
  # Backbone
  frozen_weights: 
  masks: 
  max_num_edges: 56
  backbone: resnet18  # Lighter backbone for local training
  in_channel: 3
  dilation: True
  position_embedding: sine

  # Transformer - reduced size for local training
  enc_layers: 3
  dec_layers: 3
  dim_feedforward: 1024
  hidden_dim: 128
  dropout: 0.1
  nheads: 4
  num_queries: 25
  pre_norm: True
  aux_loss: true 

  # ----- Losses ----
  loss:
    loss_components:  [shape, loop, rotation, translation]
    quality_components:  [shape, discrete, rotation, translation]
    loss_weight_dict:
      loop_loss_weight: 1.
      edge_loss_weight: 1. 
      rotation_loss_weight: 1. 
      translation_loss_weight: 1.
    stitches: simple
    lepoch: 0
    eos_coef: 0.1
    aux_loss: false
    panel_origin_invariant_loss: False
    panel_order_inariant_loss: False
    epoch_with_order_matching: 0
    order_by: shape_translation

# ------- Trainer -----
trainer: 
  dry_run: False
  random_seed: 1
  batch_size: 4  # Very small batch size for CPU training
  devices: []  # Empty list for CPU-only mode
  without_matcher: true
  epochs: 10  # Further reduced epochs for CPU testing
  lr: 0.0001  # Reduced learning rate for CPU
  lr_backbone: 5e-6
  optimizer: AdamW
  weight_decay: 1e-4
  lr_scheduling: "warm_cosine"
  lr_drop: 5
  clip_max_norm: 0.1
  early_stopping:
    window: 0.0001
    patience: 3  # Further reduced patience for CPU training
  with_visualization: false  # Disable visualizations since we're not using wandb
  return_stitches: true
  multiprocess: false  # Explicitly disable multiprocessing
  num_workers: 4  # Limit number of DataLoader workers for CPU training
